# Generated by Django 6.0.2 on 2026-07-20 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gastos",
            fields=[
                (
                    "id_gasto",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_registro", models.DateField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Pago terapeutas", "Pago terapeutas"),
                            ("Servicios", "Servicios"),
                            ("Material terapéutico", "Material terapéutico"),
                            ("Papelería y oficina", "Papelería y oficina"),
                            ("Limpieza", "Limpieza"),
                            ("Mantenimiento", "Mantenimiento"),
                            ("Equipo y mobiliario", "Equipo y mobiliario"),
                            ("Herramientas digitales", "Herramientas digitales"),
                            ("Marketing y publicidad", "Marketing y publicidad"),
                            ("Eventos y celebraciones", "Eventos y celebraciones"),
                            (
                                "Contabilidad y asesoría legal",
                                "Contabilidad y asesoría legal",
                            ),
                            ("Impuestos", "Impuestos"),
                            ("Otros", "Otros"),
                        ],
                        max_length=40,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("PAGADO", "Pagado"),
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIALMENTE CUBIERTO", "Parcialmente cubierto"),
                        ],
                        default="PENDIENTE",
                        max_length=22,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Transferencia", "Transferencia"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "id_terapeuta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gastos",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="PagoSesiones",
            fields=[
                (
                    "id_pago",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Transferencia", "Transferencia"),
                        ],
                        default="Transferencia",
                        max_length=20,
                    ),
                ),
                (
                    "paquete",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Individual", "Individual"),
                            ("Evaluacion", "Evaluación"),
                            ("4 sesiones", "4 sesiones"),
                            ("8 sesiones", "8 sesiones"),
                            ("12 sesiones", "12 sesiones"),
                            ("Paquete compartido", "Paquete compartido"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sesiones_cubiertas",
                    models.SmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Número máximo de sesiones que cubre este pago",
                        null=True,
                    ),
                ),
                ("nota_pago", models.TextField(blank=True, null=True)),
                (
                    "sesiones_asignadas",
                    models.SmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Citas asignadas al paquete",
                        null=True,
                    ),
                ),
                (
                    "id_paciente",
                    models.ForeignKey(
                        db_column="id_paciente",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pacientes.pacientes",
                    ),
                ),
            ],
            options={
                "db_table": "pago_sesiones",
                "ordering": ["-fecha_pago"],
            },
        ),
    ]
