# Generated by Django 6.0.2 on 2026-07-21 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administracion", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="personal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="honorarios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pagosesion",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pago_sesiones",
                to="pacientes.paciente",
            ),
        ),
    ]
