# Generated by Django 6.0.2 on 2026-07-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gasto",
            options={"ordering": ["-fecha"]},
        ),
        migrations.AlterModelOptions(
            name="pagosesion",
            options={"ordering": ["-fecha"]},
        ),
        migrations.RenameField(
            model_name="gasto",
            old_name="fecha_registro",
            new_name="fecha",
        ),
        migrations.RenameField(
            model_name="pagosesion",
            old_name="fecha_pago",
            new_name="fecha",
        ),
    ]
