# Generated by Django 6.0.2 on 2026-07-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion",
            "0003_alter_gasto_options_alter_pagosesion_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Honorarios", "Pago de honorarios"),
                    ("Servicios", "Servicios"),
                    ("Material terapéutico", "Material terapéutico"),
                    ("Papelería y oficina", "Papelería y oficina"),
                    ("Limpieza", "Limpieza"),
                    ("Mantenimiento", "Mantenimiento"),
                    ("Equipo y mobiliario", "Equipo y mobiliario"),
                    ("Herramientas digitales", "Herramientas digitales"),
                    ("Marketing y publicidad", "Marketing y publicidad"),
                    ("Eventos y celebraciones", "Eventos y celebraciones"),
                    ("Contabilidad y asesoría legal", "Contabilidad y asesoría legal"),
                    ("Impuestos", "Impuestos"),
                    ("Otros", "Otros"),
                ],
                max_length=40,
            ),
        ),
    ]
