# Generated by Django 6.0.7 on 2026-08-07 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0004_alter_gasto_categoria"),
        ("pacientes", "0004_tokenregistro"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeCobro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("fechas_recordadas", models.CharField(max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_cobro",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "mensajes_cobro",
                "ordering": ["paciente", "fecha_envio"],
            },
        ),
    ]
