# Generated by Django 6.0.2 on 2026-07-15 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminstracion", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gastos",
            name="id_terapeuta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pagosesiones",
            name="id_paciente",
            field=models.ForeignKey(
                db_column="id_paciente",
                on_delete=django.db.models.deletion.PROTECT,
                to="pacientes.pacientes",
            ),
        ),
    ]
