# Generated by Django 6.0.2 on 2026-07-15 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pacientes",
            fields=[
                ("nombre", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=100)),
                ("apellido_materno", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "diagnostico",
                    models.CharField(
                        blank=True,
                        help_text="Indique si el paciente tiene algún diagnostico",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "alergias",
                    models.CharField(
                        blank=True,
                        help_text="Indique si el paciente es alergico a algún médicamento, alimento, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "medicamentos",
                    models.CharField(
                        blank=True,
                        help_text="Indique si el paciente toma actualmente algún medicamento.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "escuela",
                    models.CharField(
                        help_text="Indique el nombre de la escuela a la que asiste actualmente",
                        max_length=70,
                    ),
                ),
                (
                    "nombre_padre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "edad_padre",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(80),
                        ],
                    ),
                ),
                (
                    "telefono_padre",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$",
                                "El número debe tener exactamente 10 dígitos.",
                            )
                        ],
                    ),
                ),
                (
                    "ocupacion_padre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nombre_madre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "edad_madre",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "telefono_madre",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$",
                                "El número debe tener exactamente 10 dígitos.",
                            )
                        ],
                    ),
                ),
                (
                    "ocupacion_madre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("domicilio_paciente", models.CharField(max_length=150)),
                (
                    "id_familia",
                    models.IntegerField(
                        blank=True, help_text="Identificador de hermanos", null=True
                    ),
                ),
                ("paciente_activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pacientes",
            },
        ),
    ]
