# Generated by Django 6.0.2 on 2026-07-23 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "diagnostico",
                    models.CharField(
                        blank=True,
                        help_text="Indique si el paciente tiene algún diagnostico",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enfermedad_alergia",
                    models.CharField(
                        blank=True,
                        help_text="Indique si el paciente es alergico a algún médicamento, alimento, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "medicacion",
                    models.CharField(
                        blank=True,
                        help_text="Indique si el paciente toma actualmente algún medicamento.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "escuela",
                    models.CharField(
                        help_text="Indique el nombre de la escuela a la que asiste actualmente",
                        max_length=70,
                    ),
                ),
                ("padre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "padre_telefono",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$",
                                "El número debe tener exactamente 10 dígitos.",
                            )
                        ],
                    ),
                ),
                ("padre_ocupacion", models.CharField(max_length=100)),
                ("madre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "madre_telefono",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$",
                                "El número debe tener exactamente 10 dígitos.",
                            )
                        ],
                    ),
                ),
                ("madre_ocupacion", models.CharField(max_length=100)),
                (
                    "domicilio",
                    models.CharField(
                        help_text="Indique el domicilio en el que actualmente vive el paciente",
                        max_length=150,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "factura",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si requiere facturar las citas del paciente",
                    ),
                ),
            ],
            options={
                "db_table": "pacientes",
            },
        ),
    ]
