# Generated by Django 6.0.2 on 2026-07-23 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "familia",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nombre_familia", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "familias",
            },
        ),
        migrations.AddField(
            model_name="paciente",
            name="familia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pacientes",
                to="pacientes.familia",
            ),
        ),
    ]
