# Generated by Django 6.0.2 on 2026-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_familia_paciente_familia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="domicilio",
            field=models.CharField(
                blank=True,
                help_text="Indique el domicilio en el que actualmente vive el paciente",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="escuela",
            field=models.CharField(
                blank=True,
                help_text="Indique el nombre de la escuela a la que asiste actualmente",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="madre_ocupacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="padre_ocupacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
