# Generated by Django 6.0.2 on 2026-07-21 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administracion", "0001_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "cita",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "hora",
                    models.TimeField(
                        choices=[
                            ("09:50", "09:50 A.M."),
                            ("10:40", "10:40 A.M."),
                            ("11:30", "11:30 A.M."),
                            ("12:15", "12:15 P.M."),
                            ("15:30", "03:30 P.M."),
                            ("16:20", "04:20 P.M."),
                            ("17:10", "05:10 P.M."),
                            ("18:00", "06:00 P.M."),
                            ("18:45", "06:45 P.M."),
                        ],
                        null=True,
                    ),
                ),
                ("pago_terapeuta", models.BooleanField(default=False)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="administracion.pagosesion",
                    ),
                ),
            ],
        ),
    ]
