# Generated by Django 6.0.2 on 2026-07-15 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="citas",
            fields=[
                (
                    "id_cita",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id_pago", models.UUIDField()),
            ],
        ),
    ]
