# Generated by Django 6.0.2 on 2026-07-21 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="terapeuta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
