# Generated by Django 6.0.2 on 2026-07-24 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_initial"),
        ("citas", "0002_initial"),
        ("pacientes", "0003_alter_paciente_domicilio_alter_paciente_escuela_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="fecha",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="cita",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to="pacientes.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="cita",
            name="pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to="administracion.pagosesion",
            ),
        ),
        migrations.AlterField(
            model_name="cita",
            name="terapeuta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
