# Generated by Django 6.0.2 on 2026-07-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0003_alter_cita_fecha_alter_cita_paciente_alter_cita_pago_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cita",
            old_name="pago_terapeuta",
            new_name="liquidada",
        ),
    ]
