# Generated by Django 6.0.2 on 2026-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0004_rename_pago_terapeuta_cita_liquidada"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="status",
            field=models.CharField(
                choices=[
                    ("Consultado", "Consultado"),
                    ("Confirmó y no asisitió", "Confirmó y no asisitió"),
                    ("Agendado", "Agendado"),
                ],
                max_length=22,
                null=True,
            ),
        ),
    ]
