# Generated by Django 6.0.2 on 2026-07-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0005_cita_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Consultado", "Consultado"),
                    ("Confirmó y no asisitió", "Confirmó y no asisitió"),
                    ("Agendado", "Agendado"),
                ],
                max_length=22,
                null=True,
            ),
        ),
    ]
