# Generated by Django 6.0.2 on 2026-07-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0006_alter_cita_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="nota",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cita",
            name="hora",
            field=models.CharField(
                choices=[
                    ("09:50", "09:50 A.M."),
                    ("10:40", "10:40 A.M."),
                    ("11:30", "11:30 A.M."),
                    ("12:15", "12:15 P.M."),
                    ("15:30", "03:30 P.M."),
                    ("16:20", "04:20 P.M."),
                    ("17:10", "05:10 P.M."),
                    ("18:00", "06:00 P.M."),
                    ("18:45", "06:45 P.M."),
                ],
                null=True,
            ),
        ),
    ]
