# Generated by Django 6.0.2 on 2026-07-15 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personal",
            name="date_joined",
        ),
    ]
